from sklearn.feature_extraction.text import TfidfVectorizer


def extract_keywords(text, num_keywords=5):
    """
    Extract important keywords and phrases using TF-IDF.

    Parameters:
        text (str): Input lecture text.
        num_keywords (int): Number of keywords to return.

    Returns:
        list: A list of tuples containing keyword and score.
              Example: [("machine learning", 0.42), ("artificial intelligence", 0.38)]
    """

    # Return empty list if text is empty
    if not text or not text.strip():
        return []

    # Create TF-IDF vectorizer
    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_features=1000,
        ngram_range=(1, 2)
    )

    # Transform text into TF-IDF matrix
    tfidf_matrix = vectorizer.fit_transform([text])

    # Get words and phrases generated by TF-IDF
    feature_names = vectorizer.get_feature_names_out()

    # Get TF-IDF scores for each word or phrase
    scores = tfidf_matrix.toarray()[0]

    # Combine each word/phrase with its score
    word_scores = list(zip(feature_names, scores))

    # Sort by phrase length first, then by score
    sorted_words = sorted(
        word_scores,
        key=lambda x: (
            len(x[0].split()),
            x[1]
        ),
        reverse=True
    )

    keywords = []

    for word, score in sorted_words:
        parts = word.split()

        # Skip repeated phrases like "ai ai"
        if len(parts) == 2 and parts[0] == parts[1]:
            continue

        # Skip words or phrases containing very short terms like "ai"
        if any(len(part) <= 2 for part in parts):
            continue

        # Skip weak or non-technical words
        weak_words = {
            "used", "using", "help", "helps",
            "make", "makes", "good", "new"
        }

        if any(part in weak_words for part in parts):
            continue

        # Avoid repeated concepts
        already_exists = False

        for existing_keyword, existing_score in keywords:
            if word in existing_keyword or existing_keyword in word:
                already_exists = True
                break

        if already_exists:
            continue

        # Add keyword with rounded score
        keywords.append((word,float(round(score, 2))))

        # Stop when enough keywords are collected
        if len(keywords) == num_keywords:
            break

    return keywords


if __name__ == "__main__":

    sample_text = """
    Machine learning improves education systems.
    Artificial intelligence helps students learn faster.
    Natural language processing is widely used in AI systems.
    Deep learning improves medical diagnosis.
    """

    result = extract_keywords(sample_text, 5)

    print("Top Keywords with Scores:")
    print(result)